import "./globals.css";
import type { Metadata } from "next";
// import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

// const client = new ApolloClient({
//     uri: "http://localhost:5000/graphql",
//     cache: new InMemoryCache(),
// });

export const metadata: Metadata = {
    title: "Todo App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="">{children}</body>
        </html>
    );
}
