import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Todo App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-gradient-to-r from-green-200 to-sky-300">
                {children}
            </body>
        </html>
    );
}
